# https://alacritty.org/config-alacritty.html
###########################
# General
###########################
live_config_reload = true

[shell]
program = "/usr/bin/zsh"

###########################
# Window
###########################
[window]
dimensions = { columns = 135, lines = 35 }
padding = { x = 0, y = 0 }
decorations = "None"
dynamic_padding = false
startup_mode = "Windowed"
# opacity managed by picom
opacity = 1.0
# blur managed by picom
blur = false

###########################
# Scrolling
###########################
[scrolling]
history = 10000
multiplier = 3

###########################
# Font
###########################
[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font", style = "Italic" }
bold_italic = { family = "CaskaydiaCove Nerd Font", style = "Bold Italic" }
size = 9.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

###########################
# Colors
###########################
[colors]
draw_bold_text_with_bright_colors = true

# theme: Tokyo night storm (https://github.com/alacritty/alacritty-theme)
[colors.primary]
background = "0x24283b"
foreground = "0xa9b1d6"

[colors.bright]
black = "0x444b6a"
blue = "0x7da6ff"
cyan = "0x0db9d7"
green = "0xb9f27c"
magenta = "0xbb9af7"
red = "0xff7a93"
white = "0xacb0d0"
yellow = "0xff9e64"

[colors.normal]
black = "0x32344a"
blue = "0x7aa2f7"
cyan = "0x449dab"
green = "0x9ece6a"
magenta = "0x7aa2f7"
red = "0xf7768e"
white = "0x9699a8"
yellow = "0xe0af68"

###########################
# Selection
###########################
[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

###########################
# Cursor
###########################
[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true

###########################
# Mouse
###########################
[mouse]
hide_when_typing = true
bindings = [{ mouse = "Middle", action = "PasteSelection" }]

###########################
# Debug
###########################
[debug]
log_level = "Off"
persistent_logging = false
print_events = false
render_timer = false
