# https://alacritty.org/config-alacritty.html
###########################
# General
###########################
live_config_reload = true

[shell]
program = "/usr/bin/zsh"

###########################
# Window
###########################
[window]
dimensions = { columns = 135, lines = 35 }
padding = { x = 0, y = 0 }
decorations = "None"
dynamic_padding = false
startup_mode = "Windowed"
# opacity managed by picom
opacity = 1.0
# blur managed by picom
blur = false

###########################
# Scrolling
###########################
[scrolling]
history = 10000
multiplier = 3

###########################
# Font
###########################
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
# normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
# bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
# italic = { family = "CaskaydiaCove Nerd Font", style = "Italic" }
# bold_italic = { family = "CaskaydiaCove Nerd Font", style = "Bold Italic" }
size = 8.5
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

###########################
# Colors
###########################
[colors]
draw_bold_text_with_bright_colors = true

# theme: Tokyo night storm (https://github.com/alacritty/alacritty-theme)
[colors.primary]
background = "#24283b"
foreground = "#a9b1d6"

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#7aa2f7"
red = "#f7768e"
white = "#9699a8"
yellow = "#e0af68"

###########################
# Selection
###########################
[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

###########################
# Cursor
###########################
[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true

###########################
# Mouse
###########################
[mouse]
hide_when_typing = true
bindings = [{ mouse = "Middle", action = "PasteSelection" }]

###########################
# Debug
###########################
[debug]
log_level = "Off"
persistent_logging = false
print_events = false
render_timer = false
